cert-manager:
  crds:
    enabled: true
  clusterResourceNamespace: infrastructure
  enableCertificateOwnerRef: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - infrastructure 
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - infrastructure 
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: infrastructure

  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - infrastructure 
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: infrastructure
