argocd-apps:
  projects:
    observability:
      namespace: platform
      additionalLabels: {}
      additionalAnnotations:
        "helm.sh/resource-policy": keep
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      description: Observability Services
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    infrastructure:
      namespace: platform
      additionalLabels: {}
      additionalAnnotations:
        "helm.sh/resource-policy": keep
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      description: infrastructure Services
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      namespaceResourceWhitelist:
        - group: '*'
          kind: '*'          
  applications:
    observability:
      namespace: platform
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      project: observability
      source:
        repoURL: https://github.com/ioaiaaii/micro-infra.git
        targetRevision: HEAD
        path: gitops/observability
        directory:
          recurse: true          
      # ArgoCD v2.6 or later
      # sources:
      # - chart: elasticsearch
      #   repoURL: https://helm.elastic.co
      #   targetRevision: 8.5.1
      # - repoURL: https://github.com/argoproj/argocd-example-apps.git
      #   path: guestbook
      #   targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      revisionHistoryLimit: null
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      info:
      - name: url
        value: https://argoproj.github.io/
    infrastructure:
      namespace: platform
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      project: infrastructure
      source:
        repoURL: https://github.com/ioaiaaii/micro-infra.git
        targetRevision: HEAD
        path: gitops/infrastructure
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: infrastructure
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      revisionHistoryLimit: 2
