argocd-apps:
  projects:
  - name: observability
    namespace: platform
    additionalLabels: {}
    additionalAnnotations:
      "helm.sh/resource-policy": keep
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    description: Observability Services
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  applications:
    - name: observability
      namespace: platform
      destination:
        namespace: observability
        server: https://kubernetes.default.svc
        createNamespace: true        
      project: observability
      source:
        path: gitops/observability
        repoURL: https://github.com/ioaiaaii/micro-infra.git
        targetRevision: HEAD
        directory:
          recurse: true
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
