apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert
  namespace: <your-namespace>
spec:
  commonName: "zero-trust"
  secretName: client-cert
  issuerRef:
    name: mtls-ca-issuer   # Use the dedicated mTLS ClusterIssuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
