apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ioaiaaii-live
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  destination:
    namespace: ioaiaaii-live
    server: https://kubernetes.default.svc
  project: products
  source:
    repoURL: 'https://github.com/ioaiaaii/ioaiaaii.net.git'
    path: deploy/helm/ioaiaaii
    targetRevision: "v*"           # Match tags that start with 'v'
    tracking: latest               # Automatically track the latest matching tag
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
