apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ioaiaaii-cd
  namespace: platform
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: ioaiaaii
        repo: ioaiaaii.net
        labels:
        - preview
  template:
    metadata:
      name: 'ioaiaaii-{{.branch_slug}}-{{.number}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io      
    spec:
      source:
        repoURL: https://github.com/ioaiaaii/ioaiaaii.net.git
        targetRevision: '{{.head_sha}}'
        path: deploy/helm/ioaiaaii
        helm:
          parameters:
          - name: web.image.tag
            value: '{{.branch_slug}}'
          - name: web.image.pullPolicy
            value: Always
          - name: ingress.hostname
            value: '{{.branch_slug}}.ioaiaaii.net'
          - name: tls[0].hosts[0]
            value: '{{.branch_slug}}.ioaiaaii.net'
          - name: tls[0].secretName
            value: 'letsencrypt-cluster-cert-ioaiaaii'        
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/instance: 'ioaiaaii-{{.branch_slug}}-{{.number}}'
          annotations:
            argocd.argoproj.io/tracking-id: >-
              'ioaiaaii-{{.branch_slug}}-{{.number}}:/Namespace:ioaiaaii-{{.branch_slug}}-{{.number}}/ioaiaaii-{{.branch_slug}}-{{.number}}'
        syncOptions:
        - CreateNamespace=true              
      project: products
      destination:
        server: https://kubernetes.default.svc
        namespace: 'ioaiaaii-{{.branch_slug}}-{{.number}}'
