tempo:
  persistence:
    enabled: true
    size: "20Gi"
  tempo:
    retention: "36h"
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 100Mi 
  serviceMonitor:
    enabled: true
