tempo:
  persistence:
    enabled: true
    size: "10Gi"
  tempo:
    retention: "36h"
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 300Mi
    ingester:
      max_block_bytes: 1
      max_block_duration: 5s
      flush_check_period: 1s
      trace_idle_period: 1s        
  serviceMonitor:
    enabled: true
