argo-cd:
  global:
    networkPolicy:
      create: false
      defaultDenyIngress: false
    # priorityClassName: system-cluster-critical
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: infrastructure
    # Default affinity preset for all components
    affinity:
      # -- Default pod anti-affinity rules. Either: `none`, `soft` or `hard`
      podAntiAffinity: soft
      # Node affinity rules
      nodeAffinity:
        # -- Default node affinity rules. Either: `none`, `soft` or `hard`
        type: soft
        matchExpressions:
          - key: dedicated
            operator: In
            values:
            - infrastructure
    logging:
      format: json
      level: error    
  dex:
    enabled: false
  redis:
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
  controller:        
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  server:
    autoscaling:
      enabled: true
      maxReplicas: 2
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  repoServer:
    name: repo-server
    autoscaling:
      enabled: true
      maxReplicas: 2
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
    resources:
     limits:
       cpu: 50m
       memory: 128Mi
     requests:
       cpu: 10m
       memory: 64Mi
  applicationSet:
    resources:
     limits:
       cpu: 50m
       memory: 128Mi
     requests:
       cpu: 10m
       memory: 64Mi
  configs:
    params:
      server.insecure: true
    repositories:
      micro-helm-repo:
        name: micro-infra-charts
        type: git
        url: https://github.com/ioaiaaii/micro-infra.git
      argo-helm-repo:
        name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
      products-ioaiaiii:
        name: ioaiaiii.net
        type: git
        url: https://github.com/ioaiaaii/ioaiaaii.net.git
      prometheus-community-repo:
        name: prometheus-community
        type: git
        url: https://github.com/prometheus-community/helm-charts.git
