ingress-nginx:
  controller:
    service:
      annotations: 
        cloud.google.com/network-tier: Standard
    autoscaling:
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
