ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    service:
      annotations: 
        cloud.google.com/network-tier: Standard
    autoscaling:
      enabled: true
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 100Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - infrastructure 
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: infrastructure
    metrics:
      serviceMonitor: true
    config:
      enable-opentelemetry: "true"
      opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
      opentelemetry-trust-incoming-span: "true"
      otlp-collector-host: "otel-collector.observability.svc.cluster.local"
      otlp-collector-port: "4317"
      otel-max-queuesize: "2048"
      otel-schedule-delay-millis: "5000"
      otel-max-export-batch-size: "512"
      otel-service-name: "nginx-controller" # Opentelemetry resource name
      otel-sampler: "AlwaysOn" # Also: AlwaysOff, TraceIdRatioBased
      otel-sampler-ratio: "0.5" #50% probability to sample requests
      otel-sampler-parent-based: "true"
