ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    service:
      annotations: 
        cloud.google.com/network-tier: Standard
    autoscaling:
      enabled: true
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    resources:
      limits:
        cpu: 50m
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 150Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - infrastructure
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: infrastructure
    metrics:
      serviceMonitor: true
    config:
      #tracing
      enable-opentelemetry: "true"
      opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
      opentelemetry-trust-incoming-span: "true"
      otlp-collector-host: "otel-collector.observability.svc.cluster.local"
      otlp-collector-port: "4317"
      otel-max-queuesize: "2048"
      otel-schedule-delay-millis: "5000"
      otel-max-export-batch-size: "512"
      otel-service-name: "nginx-controller" # Opentelemetry resource name
      otel-sampler: "TraceIdRatioBased" # Also: AlwaysOff, TraceIdRatioBased
      otel-sampler-ratio: "0.1" #probability to sample requests
      otel-sampler-parent-based: "true"
      opentelemetry-custom-attributes: |
        client.ip=$http_x_forwarded_for
              
      #proxing pass source IP information
      #https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-proxy-protocol
      use-forwarded-headers: "true"
      use-proxy-protocol: "true"
      compute-full-forwarded-for: "true"
      proxy-add-original-uri-header: "true"
  
      #hardening
      force-ssl-redirect: "true"      
      ssl-protocols: "TLSv1.3"
      ssl_prefer_server_ciphers: 'off'
      hide-headers: Server,X-Powered-By
      #logging
      log-format-escape-json: "true"
      log-format-upstream: >-
        {
        "time":"$time_iso8601",
        "client_ip":"$http_x_forwarded_for",
        "forwarded_for":"$http_x_forwarded_for",
        "remote_addr":"$remote_addr",
        "body_bytes_sent":"$body_bytes_sent",
        "bytes_sent": $bytes_sent,
        "host":"$host",
        "http_referrer":"$http_referer",
        "http_user_agent":"$http_user_agent",
        "proxy_add_x_forwarded_for":"$proxy_add_x_forwarded_for",
        "proxy_upstream_name":"$proxy_upstream_name",
        "request":"$request",
        "request_id":"$req_id",
        "request_length":"$request_length",
        "request_method":"$request_method",
        "request_path":"$uri",
        "request_proto":"$server_protocol",
        "request_query":"$args",
        "request_time":"$request_time",
        "status":"$status",
        "upstream_addr":"$upstream_addr",
        "upstream_response_length":"$upstream_response_length",
        "upstream_response_time":"$upstream_response_time",
        "upstream_status":"$upstream_status"
        }
