apiVersion: v2
name: cluster-autoscaler
description: A Helm meta-chart for managing Cluster Autoscaler
type: application
version: 1.0.0
appVersion: "1.31.0"
dependencies:
  - name: cluster-autoscaler
    version: 9.43.0
    repository: https://kubernetes.github.io/autoscaler
