cluster-autoscaler:
  cloudProvider: gce
  autoDiscovery:
    clusterName: ioaiaaii
  autoscalingGroupsnamePrefix:
    - name: workers-base-pool
      minSize: 2
      maxSize: 3

  extraArgs:
    logtostderr: true
    stderrthreshold: info
    v: 4
    # write-status-configmap: true
    # status-config-map-name: cluster-autoscaler-status
    leader-elect: false
    # leader-elect-resource-lock: endpoints
    # skip-nodes-with-local-storage: true
    # expander: random
    balance-similar-node-groups: true
    # min-replica-count: 0
    scale-down-enabled: true    
    scale-down-utilization-threshold: 0.5
    scale-down-non-empty-candidates-count: 30
    max-node-provision-time: 10m0s
    scale-down-delay-after-add: 5m
    scale-down-delay-after-delete: 0s
    scale-down-delay-after-failure: 3m
    scale-down-unneeded-time: 5m
    # skip-nodes-with-system-pods: true
    # balancing-ignore-label_1: first-label-to-ignore
    # balancing-ignore-label_2: second-label-to-ignore
