cluster-autoscaler:
  cloudProvider: gce
  autoDiscovery:
    clusterName: ioaiaaii
  autoscalingGroupsnamePrefix:
    - name: gke-ioaiaaii-workers-base-pool
      minSize: 1
      maxSize: 2
    - name: gke-ioaiaaii-infrastructure
      minSize: 1
      maxSize: 3
  extraArgs:
    leader-elect: false
    scale-down-utilization-threshold: 0.6
    scale-down-unneeded-time: 5m    
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - infrastructure 
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: infrastructure
  resources:
    limits:
      cpu: 10m
      memory: 100Mi
    requests:
      cpu: 5m
      memory: 50Mi
