cluster-autoscaler:
  cloudProvider: gce
  autoDiscovery:
    clusterName: ioaiaaii
  autoscalingGroupsnamePrefix:
    - name: gke-workers-base-pool
      minSize: 2
      maxSize: 3

  extraArgs:
    leader-elect: false
